In [1]:
# decision tree is obvious approach

#nn approach
'''
many categorical variables
initial option: one hot
additional option: encodings
'''

import csv
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import normalize

train_path = "train.csv"
test_path = "test.csv"

# Read the CSV file into a pandas DataFrame
train_frame = pd.read_csv(train_path)
test_frame = pd.read_csv(train_path)



In [2]:
# Display the DataFrame
print(train_frame)
print(test_frame)

# print(train_frame.describe())
# print(test_frame.describe())

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa 

In [3]:

planets = train_frame.loc[:,"HomePlanet"].to_numpy(na_value="")
print(planets)
print(planets.shape)

['Europa' 'Earth' 'Europa' ... 'Earth' 'Europa' 'Europa']
(8693,)


In [4]:
def one_hot_encode(categories):
    # Convert categories to numerical labels
    label_encoder = LabelEncoder()
    labels = label_encoder.fit_transform(categories)

    # Create an identity matrix of size (n, n) where n is the number of unique labels
    n=len(np.unique(labels))
    print(f"Number of unique labels = {n}")
    identity_matrix = np.eye(n)

    # Convert labels to one-hot encoding
    one_hot_encoding = identity_matrix[labels]

    return one_hot_encoding
# Example usage

oh_planets = one_hot_encode(planets)
print(oh_planets)


Number of unique labels = 4
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [5]:
destination = train_frame.loc[:,"Destination"].to_numpy(na_value="")
oh_dest = one_hot_encode(destination)
print(oh_dest)

Number of unique labels = 4
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [6]:
sleep = train_frame.loc[:,"CryoSleep"].to_numpy()
oh_sleep = one_hot_encode(sleep)
print(oh_sleep)
vip = train_frame.loc[:,"VIP"].to_numpy()
oh_vip = one_hot_encode(vip)
print(oh_vip)

transported = train_frame.loc[:,"Transported"].to_numpy()
oh_transported = one_hot_encode(transported)
print(oh_transported)

Number of unique labels = 3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Number of unique labels = 3
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Number of unique labels = 2
[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [7]:
cabin = train_frame.loc[:,"Cabin"].to_list()

In [8]:
import math


list1, list2, list3 = split_arrays(cabin)

oh_c1 = one_hot_encode(list1)
oh_c2 = np.array(list2,dtype="float64").reshape((8693,1))
oh_c3 = one_hot_encode(list3)

print(oh_c1,oh_c2,oh_c3)

Number of unique labels = 9
Number of unique labels = 3
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[   0.]
 [   0.]
 [   0.]
 ...
 [1500.]
 [ 608.]
 [ 608.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [9]:



pid=train_frame.loc[:,"PassengerId"].to_list()
print(pid[:50])

['0001_01', '0002_01', '0003_01', '0003_02', '0004_01', '0005_01', '0006_01', '0006_02', '0007_01', '0008_01', '0008_02', '0008_03', '0009_01', '0010_01', '0011_01', '0012_01', '0014_01', '0015_01', '0016_01', '0017_01', '0017_02', '0020_01', '0020_02', '0020_03', '0020_04', '0020_05', '0020_06', '0022_01', '0024_01', '0025_01', '0026_01', '0028_01', '0030_01', '0031_01', '0031_02', '0031_03', '0034_01', '0035_01', '0036_01', '0038_01', '0039_01', '0041_01', '0043_01', '0044_01', '0044_02', '0044_03', '0045_01', '0045_02', '0050_01', '0051_01']


In [10]:
def split_arrays(arr):
    list1, list2 = [], []
    for s in arr:
        try:
            split_s = s.split('_')
            if len(split_s) == 2:
                list1.append(int(split_s[0]))
                list2.append(int(split_s[1]))
        except:
            list1.append(10000)
            list2.append(1)
    return list1, list2
    
list1, list2= split_arrays(pid)

id1= np.array(list1,dtype="float64")
id2 = np.array(list2, dtype="float64")
print(id1,id2)

[1.000e+00 2.000e+00 3.000e+00 ... 9.279e+03 9.280e+03 9.280e+03] [1. 1. 1. ... 1. 1. 2.]


In [11]:
#raw quantities
# Age, RoomService, FoodCourt, ShoppingMall, Spa, VRDeck
rs=train_frame.iloc[:,[5,7,8,9,10,11]].to_numpy(dtype="float64")
print(rs)
print(rs.shape)


[[3.900e+01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [2.400e+01 1.090e+02 9.000e+00 2.500e+01 5.490e+02 4.400e+01]
 [5.800e+01 4.300e+01 3.576e+03 0.000e+00 6.715e+03 4.900e+01]
 ...
 [2.600e+01 0.000e+00 0.000e+00 1.872e+03 1.000e+00 0.000e+00]
 [3.200e+01 0.000e+00 1.049e+03 0.000e+00 3.530e+02 3.235e+03]
 [4.400e+01 1.260e+02 4.688e+03 0.000e+00 0.000e+00 1.200e+01]]
(8693, 6)


In [12]:
multicat=[oh_planets,oh_dest,oh_transported]
cat=[oh_c1,oh_c2,oh_c3]
binary=[oh_vip,oh_sleep]

for layer in [multicat,cat,binary]:
    for val in layer:
        print(val.shape)

(8693, 4)
(8693, 4)
(8693, 2)
(8693, 9)
(8693, 1)
(8693, 3)
(8693, 3)
(8693, 3)


In [13]:
oh_transported[:,1].shape

(8693,)

In [14]:
res=np.concatenate((oh_planets,oh_dest,oh_transported,oh_c1,oh_c2,oh_c3,oh_vip,oh_sleep),axis=1)
print(res.shape)

(8693, 29)


In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils as utils


c:\Users\BrandonFafata\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [23]:
inp = torch.Tensor(res).double()
labs = torch.Tensor(oh_transported[:,1].reshape((8693,1))).double()

In [31]:

# Define the network architecture

model = nn.Sequential(
    nn.Linear(29, 128),
    nn.ReLU(),
    nn.Linear(128, 128),
    nn.ReLU(),
    nn.Linear(128, 1),
    nn.Sigmoid(),
)

model = model.double()  # To make it use float64

# Define the loss and the optimizer
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

#
dataset = utils.data.TensorDataset(inp,labs)
loader = utils.data.DataLoader(dataset,batch_size=50)

def train_model(model, criterion, optimizer, inputs, labels, num_epochs=25):
    
    for epoch in range(num_epochs):
        losses=[]
        for input,labels in loader:
            # print(input.shape)
            # print(labels.shape)
            optimizer.zero_grad()



            # forward + backward + optimize
            outputs = model(input)
            #print(outputs.shape)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            losses.append(loss.item())

        print(f'Epoch {epoch+1}/{num_epochs} Loss: {np.mean(np.array(losses))}')

    print('Finished Training')

train_model(model,criterion,optimizer,inp,labs)

Epoch 1/25 Loss: 0.7106847507323304
Epoch 2/25 Loss: 0.6934184537785831
Epoch 3/25 Loss: 0.6931590887559033
Epoch 4/25 Loss: 0.6928549652924183
Epoch 5/25 Loss: 0.7224323660379631
Epoch 6/25 Loss: 0.6916439803529134
Epoch 7/25 Loss: 0.692136667768514
Epoch 8/25 Loss: 0.6952623655331658
Epoch 9/25 Loss: 0.6900183814830264
Epoch 10/25 Loss: 0.6883439412965827
Epoch 11/25 Loss: 0.6883839791829199
Epoch 12/25 Loss: 0.6859850346095722
Epoch 13/25 Loss: 0.6851787240000194
Epoch 14/25 Loss: 0.6844788094777183
Epoch 15/25 Loss: 0.7053574996503365
Epoch 16/25 Loss: 0.6859936742099607
Epoch 17/25 Loss: 0.6761343424479904
Epoch 18/25 Loss: 0.6778085845155241
Epoch 19/25 Loss: 0.7484817034185284
Epoch 20/25 Loss: 0.6826340490569643
Epoch 21/25 Loss: 0.6795821898860548
Epoch 22/25 Loss: 0.6802998926477118
Epoch 23/25 Loss: 0.678131861448068
Epoch 24/25 Loss: 0.6777277449559376
Epoch 25/25 Loss: 0.6774625253851196
Finished Training
